# Generated by Django 5.1.7 on 2025-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_rename_fecha_hora_cita_fecha_cita_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
    ]
