# Generated by Django 5.2 on 2025-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0004_alter_cita_especialidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
