# Generated by Django 5.2 on 2025-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_created_at_cita_updated_at_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dias_trabajo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='dias_laborables',
            field=models.CharField(default='0,1,2,3,4', help_text='Días laborables (0=Lunes, 6=Domingo), separados por comas', max_length=13),
        ),
    ]
