# Generated by Django 5.2 on 2025-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_doctor_dias_trabajo_doctor_dias_laborables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('medicina_general', 'Medicina General'), ('pediatria', 'Pediatría'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología y Obstetricia'), ('oftalmologia', 'Oftalmología'), ('traumatologia', 'Traumatología'), ('psiquiatria', 'Psiquiatría'), ('neurologia', 'Neurología'), ('endocrinologia', 'Endocrinología'), ('otorrinolaringologia', 'Otorrinolaringología'), ('urologia', 'Urología'), ('gastroenterologia', 'Gastroenterología'), ('oncologia', 'Oncología'), ('reumatologia', 'Reumatología'), ('nefrologia', 'Nefrología'), ('hematologia', 'Hematología'), ('infectologia', 'Infectología'), ('medicina_interna', 'Medicina Interna'), ('cirugia_general', 'Cirugía General')], max_length=100),
        ),
    ]
