# Generated by Django 5.2 on 2025-04-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='verificado_por',
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificacion_1',
            field=models.FileField(blank=True, null=True, upload_to='documentos_doctores/%(id)s/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificacion_2',
            field=models.FileField(blank=True, null=True, upload_to='documentos_doctores/%(id)s/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificacion_3',
            field=models.FileField(blank=True, null=True, upload_to='documentos_doctores/%(id)s/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='documento_licencia',
            field=models.FileField(blank=True, null=True, upload_to='documentos_doctores/%(id)s/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(max_length=50),
        ),
    ]
