# Generated by Django 5.2 on 2025-04-04 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_remove_doctor_verificado_por_doctor_certificacion_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dias_laborables',
            field=models.CharField(default='0,1,2,3,4', max_length=13),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('medicina_general', 'Medicina General'), ('pediatria', 'Pediatría'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología'), ('oftalmologia', 'Oftalmología'), ('psiquiatria', 'Psiquiatría'), ('traumatologia', 'Traumatología')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
