# Generated by Django 5.2 on 2025-04-04 19:47

import citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_alter_doctor_dias_laborables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificacion_1',
            field=models.FileField(blank=True, null=True, upload_to=citas.models.certificacion_path),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certificacion_2',
            field=models.FileField(blank=True, null=True, upload_to=citas.models.certificacion_path),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certificacion_3',
            field=models.FileField(blank=True, null=True, upload_to=citas.models.certificacion_path),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='documento_licencia',
            field=models.FileField(blank=True, null=True, upload_to=citas.models.documento_licencia_path),
        ),
    ]
